#!/bin/sh
set -e

case "$1" in
    purge)
        if command -v deb-systemd-helper >/dev/null; then
            deb-systemd-helper purge system-monitor.service >/dev/null || true
            deb-systemd-helper unmask system-monitor.service >/dev/null || true
        fi
        ;;
esac

exit 0
